config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  get 'categories/update'
  get 'categories/destroy'
  get 'categories/new'
  get 'categories/edit'
  get 'ctegories/resource'
  root 'pages#home'
  get '/about', to: 'about#index'
  get 'contact', to: 'contact#index'
  resources :posts, :projects, :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
company = {
  "mail" => "info@ablele.com",
  "number" => "48805663",
  "name" => "Ainotek"
}

	add_flash_types :success, :danger, :warning
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category only: [:show, :update, :destroy, :edit  ]
  
  def index
    @categories = Category.all
  end

  def show
  end

  def update
    @category.update(Category_params)
    redirect_to category_path(@category.id)
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  def new
    @category = Category.new 
  end

  def create
    @category = Category.create(category_params)
    redirect_to categories_path
  end

  def edit
  end

  private

  def category_params
    params.require(:category).permit(:name, :slug)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    end
end

app/controllers/ctegories_controller.rb
class CtegoriesController < ApplicationController
  def resource
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @connexion = false
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    

    def index
    	cookies[:username] = {
    		value: "Jhon",
    		expires: 1.month.from_now
    	}

        @posts = Post.all
        @categories = Category.all

        respond_to do |format|
        	format.html
        	format.json { render json: @posts }
        end
    end

    def show
    	set_post
    end

    def edit
    	set_post
    end 

    def update
    	set_post
    	@post.update(post_params)
    	flash[:success] = 
    	redirect_to post_path, success: "Successfully edited!"
    end


    def new
    	@post = Post.new
    end

    def create
    	@post = Post.create(post_params)
    	redirect_to post_path(@post.id), success: "Successfully created!"
    end

    def destroy
    	set_post
    	@post.destroy
    	redirect_to posts_path, success: "Successfully deleted!"
    end

    private

    def post_params
    	params.require(:post).permit(:title, :content)    	
    end

    def set_post
    	@post = Post.find(params[:id])
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :set_project only: [:show, :update, :destroy, :edit]

    def index
    	@project = Project.all
        @posts = Post.all
        @categories = Category.all
    end

    def show
    end

    def edit
    end 

    def update
    	@project.update(project_params)
    	redirect_to project_path
    end


    def new
    	@project = Project.new
    end

    def create
    	@project = Project.create(project_params)
    	redirect_to project_path(@project.id)
    end

    def destroy
    	@project.destroy
    	redirect_to projects_path
    end

    private

    def project_params
    	params.require(:project).permit(:title, :content)
    end

    def set_project
    	@project = Project.find(params[:id])
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/ctegories_helper.rb
module CtegoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<!-- Page Header -->
<div class="inner-page-header">
	<div class="container">
		<div class="row">

			<!-- Page Title -->
			<div class="col-md-8">
				<h1 class="title">Edditing Categories</h1>
				<div class="subtitle">There are many variations of passages </div>
			</div>
			<!-- /Page Title -->

			<!-- Breadcrumbs -->
			<div class="col-md-4">
				<ul class="breadcrumb">
					<li><i class="fa fa-fw fa-home"></i> <a href="<%= root_path %>">Home</a></li>
					<li><a href="<%= posts_path %>">Blog</a></li>
					<li>Categories</li>
				</ul>
			</div>
			<!-- /Breadcrumbs -->

		</div>
	</div>
</div>
<!-- /Page Header -->

<%= form_for @category do |f| %>


	<h1 class="title">Add Categories</h1>
	<div class="form-group">
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.text_field :slug, class: 'form-control' %>
	</div>

	<div class="form-group">
		<button class="btn btn-red" type="reset">Annuler</button>
		<button class="btn btn-blue" type="submit">Edit category</button>
	</div>

<% end %>

app/views/categories/index.html.erb
<!-- Page Header -->
<div class="inner-page-header">
	<div class="container">
		<div class="row">

			<!-- Page Title -->
			<div class="col-md-8">
				<h1 class="title">Blog - Categories List</h1>
				<div class="subtitle">There are many variations of passages </div>
			</div>
			<!-- /Page Title -->

			<!-- Breadcrumbs -->
			<div class="col-md-4">
				<ul class="breadcrumb">
					<li><i class="fa fa-fw fa-home"></i> <a href="<%= root_path %>">Home</a></li>
					<li><a href="<%= posts_path %>">Blog</a></li>
					<li>Categories</li>
				</ul>
			</div>
			<!-- /Breadcrumbs -->

		</div>
	</div>
</div>
<!-- /Page Header -->
<div class="title">Categories</div>

<table>
							<a href="<%= new_category_path %>"><button class="btn btn-rounded btn-blue">
							<i class="icon fa fa-plus" title="Add"></i>	
							 </button></a>


	<thead>
		<tr>
			<td>ID</td>
			<td>Nom</td>
			<td>Actions</td>	
		</tr>
	</thead>>

		<tbody>
			<%= @categories.each do |category| %>
				<tr>
					<td><%= category.id%></td>
					<td><%= category.name%></td>
					<td>									
						<!-- controls -->
						<div>
							<a href="<%= edit_category_path(category.id) %>"><button class="btn btn-rounded btn-theme">
							<i class="icon fa fa-edit" title="Edit"></i>	
							 </button></a>

							<a href="<%= category_path(category.id) %>" class="btn btn-rounded btn-red"
								data-confirm="Delete it?"
								data-method="delete">
							<i class="icon fa fa-trash" title="Delete"></i>	
							 </a>
						</div>
						<!-- /controls -->
					</td>
				</tr>
			<% end %>
		</tbody>
</table>



				<!-- Widget: Categories -->
				<div class="widget">

					<ul class="sidebar-menu">
						<li><a href="#">Photography</a></li>
						<li><a href="#">Photography</a></li>
						<li><a href="#">Illustration</a></li>
						<li><a href="#">Web-Design</a></li>
						<li><a href="#">Art</a></li>
						<li><a href="#">Coding</a></li>
					</ul>

				</div>
				<!-- /Widget: Categories -->

app/views/categories/new.html.erb
<!-- Page Header -->
<div class="inner-page-header">
	<div class="container">
		<div class="row">

			<!-- Page Title -->
			<div class="col-md-8">
				<h1 class="title">Adding Categories</h1>
				<div class="subtitle">There are many variations of passages </div>
			</div>
			<!-- /Page Title -->

			<!-- Breadcrumbs -->
			<div class="col-md-4">
				<ul class="breadcrumb">
					<li><i class="fa fa-fw fa-home"></i> <a href="<%= root_path %>">Home</a></li>
					<li><a href="<%= posts_path %>">Blog</a></li>
					<li>Categories</li>
				</ul>
			</div>
			<!-- /Breadcrumbs -->

		</div>
	</div>
</div>
<!-- /Page Header -->

<%= form_for @category do |f| %>


	<h1 class="title">Add Categories</h1>
	<div class="form-group">
		<%= f.text_field :name, placeholder:'Nom', class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.text_field :slug, placeholder:'Url', class: 'form-control' %>
	</div>

	<div class="form-group">
		<button class="btn btn-red" type="reset">Annuler</button>
		<button class="btn btn-blue" type="submit">Créer la category</button>
	</div>

<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/contact/index.html.erb
<!-- Page Header -->
<div class="inner-page-header">
    <div class="container">
        <div class="row">

            <!-- Page Title -->
            <div class="col-md-8">
                <h1 class="title">Contact</h1>
                <div class="subtitle">There are many variations of passages </div>
            </div>
            <!-- /Page Title -->

            <!-- Breadcrumbs -->
            <div class="col-md-4">
                <ul class="breadcrumb">
                    <li><i class="fa fa-fw fa-home"></i> <a href="#">Home</a></li>
                    <li>Contact</li>
                </ul>
            </div>
            <!-- /Breadcrumbs -->

        </div>
    </div>
</div>
<!-- /Page Header -->

<!-- Main -->
<main class="main-container">

    <!-- Section: Contact -->
    <section id="contact" class="section section-small">
        <div class="container">

            <!-- Section Content -->
            <div class="row">

                <!-- Contact Information -->
                <div class="col-sm-5">

                    <h3>Information</h3>
                    <p>
                        There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                        alteration in some form.
                    </p>

                    <ul class="list-lined">
                        <li>
                            <i class="icon fa fa-fw fa-globe"></i><span>Address</span> 988782, Our Street, L.A.
                            <small style="float: right">
                                <a href="https://maps.google.com/maps?q=221B+Baker+Street,+London,+United+Kingdom&amp;hl=en&amp;t=v&amp;hnear=221B+Baker+St,+London+NW1+6XE,+United+Kingdom" class="iframe-popup">(See on Map)</a>
                            </small>
                        </li>
                        <li><i class="icon fa fa-fw fa-envelope"></i><span>E-mail</span> clients@example.com</li>
                        <li><i class="icon fa fa-fw fa-phone"></i><span>Phone</span> +1 (201) 987-1185</li>
                    </ul>

                    <h3>Work Time</h3>

                    <ul class="list-lined">
                        <li><i class="icon fa fa-clock-o"></i> <span>Mon - Sat</span> 9:00 - 19:00</li>
                        <li><i class="icon fa fa-clock-o"></i> <span>Sunday</span> Closed</li>
                    </ul>

                </div>
                <!-- /Contact Information -->

                <!-- Contact Form -->
                <div class="col-sm-7">

                    <div class="contact-form">

                        <h3>Send Message</h3>

                        <form class="form-ajax" method="post">
                            <input type="hidden" name="form" value="Contact Page">
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <input type="text" name="name" class="form-control" placeholder="Your Name... *" required>
                                </div>
                                <div class="form-group col-md-6">
                                    <input type="email" name="email" class="form-control" placeholder="E-mail address... *" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <textarea name="message" class="form-control" placeholder="Message... "></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12 text-center">
                                    <button type="submit" class="btn btn-theme"><i class="fa fa-fw fa-paper-plane-o"></i> Send Message</button>
                                </div>
                            </div>
                        </form>

                    </div>


                </div>
                <!-- /Contact Form -->

            </div>
            <!-- /Section Content -->

        </div>
    </section>
    <!-- /Section: Contact -->

</main>
<!-- /Main -->

app/views/ctegories/resource.html.erb
<h1>Ctegories#resource</h1>
<p>Find me in app/views/ctegories/resource.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ainotek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <!-- Page title -->
        <!-- Meta -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Favicon -->
        <link rel="shortcut icon" href="("img/favicon.png")">
  </head>

  <body>
  <!-- Header -->
  <header id="home" class="header">
      <nav id="navigation" class="navbar affix">


          <!-- Top Line -->
          <div class="top-line">
              <div class="container">
                  <div class="row">

                      <!-- Company Information -->
                      <div class="col-md-7 contact-information">
                          <ul class="list-inline">
                              <li><i class="icon fa fa-fw fa-phone"></i> <%= "48805663" %> </li>
                              <li><i class="icon fa fa-fw fa-envelope-o"></i> <%= "info@ainotek.com" %> </li>
                          </ul>
                      </div>
                      <!-- /Company Information -->

                      <!-- Search Form -->
                      <div class="col-md-3">
                          <div class="search-form">
                              <input type="email" class="form-control" placeholder="Search..." required>
                              <button class="btn btn-search"><i class="fa fa-fw fa-search"></i></button>
                          </div>
                      </div>
                      <!-- /Search Form -->

                      <!-- User Cabinet Links -->
                      <div class="col-md-2 user-cabinet-links">
                          <ul class="list-inline">
                              <li><a href="#" data-toggle="modal" data-target="#sign-in"><i class="icon fa fa-fw fa-sign-in"></i> Sign in</a></li>
                              <li><a href="#" data-toggle="modal" data-target="#sign-up"><i class="icon fa fa-fw fa-edit"></i> Sign up</a></li>
                          </ul>
                      </div>
                      <!-- /User Cabinet Links -->

                  </div>
              </div>
          </div>
          <!-- /Top Line -->


          <!-- Toggle Button -->
          <div class="top-line-slide">
              <div class="top-line-toggle in">
                  <i class="icon fa fa-fw fa-angle-down"></i>
              </div>
          </div>
          <!-- /Toggle Button -->

          <!-- Top Menu -->
          <div class="top-menu">
              <div class="container">

                  <div class="row">
                      <div class="col-md-12">

                          <!-- Navigation Header -->
                          <div class="navbar-header">

                              <!-- Toggle Button -->
                              <button type="button"
                                      class="navbar-toggle collapsed"
                                      data-toggle="collapse"
                                      data-target="#main-menu"
                                      aria-expanded="false"
                                      aria-controls="main-menu">

                                  <span class="sr-only">Toggle Navigation</span>
                                  <span class="icon-bar"></span>
                                  <span class="icon-bar"></span>
                                  <span class="icon-bar"></span>

                              </button>
                              <!-- /Toggle Button -->

                              <!-- Brand -->
                              <a href="#" class="brand">
                                  <div class="logo-big">
                                      <%= image_tag("logo.png" , :alt => "") %>
                                  </div>
                                  <div class="logo-small">
                                      <%= image_tag("logo-small.png" , :alt => "") %>
                                  </div>
                              </a>
                              <!-- /Brand -->

                          </div>
                          <!-- /Navigation Header -->

                          <!-- Navigation -->
                          <div id="main-menu" class="navbar-collapse collapse">
                              <ul class="nav navbar-nav navbar-right">
                                  <li>
                                      <a href="<%= root_path %>">Accueil</a>
                                  </li>
                                  <li>
                                      <a href="<%= about_path %>">A propos</a>
                                  </li>
                                  <li>
                                      <a href="<%= projects_path %>">Portfolio</a>
                                  </li>
                                  <li>
                                      <a href="<%= posts_path %>">Blog</a>
                                  </li>
                                  <li><a href="<%= contact_path %>">Contact</a></li>
                              </ul>
                          </div>
                          <!-- /Navigation -->

                      </div>
                  </div>
              </div>
          </div>
          <!-- Top Menu -->

      </nav>
  </header>
  <!-- /Header -->
  <% flash.each do |type, msg| %>
    <div class="alert alert-<%= type %>" role="alert">
      <%= msg %>
    </div>
  <% end %>


    <%= yield %>


<!-- Footer -->
<footer class="footer section section-small no-pb bg-dark">
    <div class="container">
        <div class="row">

            <!-- Footer Column -->
            <div class="col-sm-3">
                <div class="brand">
                    Aino<span class="text-theme">Tek</span>
                </div>
                <p>
                    There are many variations of passages of Lorem Ipsum available.
                </p>
                <div class="title">Our Address:</div>
                <p>
                    988782, Our Street, L.A.
                </p>
                <ul class="list">
                    <li><span>Phone:</span> +1 (201) 987-1185</li>
                    <li><span>E-mail:</span> clients@example.com</li>
                </ul>
            </div>
            <!-- /Footer Column -->

            <!-- Footer Column -->
            <div class="col-sm-2">
                <div class="h4 title">Navigation:</div>
                <ul class="list menu">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Features</a></li>
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <!-- /Footer Column -->

            <!-- Footer Column -->
            <div class="col-sm-3">
                <div class="h4 title">From Blog</div>
                <div class="media post">
                    <div class="media-left">
                        <div class="image">
                            <%= image_tag("last-post-01.jpg" , :alt => "") %>
                        </div>
                    </div>
                    <div class="media-body">
                        <p class="text">
                            It is a long established fact that a reader will be distracted.
                        </p>
                        <a href="#">Read more <i class="fa fa-angle-double-right"></i> </a>
                    </div>
                </div>
                <div class="media post">
                    <div class="media-left">
                        <div class="image">
                            <%= image_tag("last-post-02.jpg" , :alt => "") %>
                        </div>
                    </div>
                    <div class="media-body">
                        <p class="text">
                            It is a long established fact that a reader will be distracted.
                        </p>
                        <a href="#">Read more <i class="fa fa-angle-double-right"></i> </a>
                    </div>
                </div>
            </div>
            <!-- /Footer Column -->

            <!-- Footer Column -->
            <div class="col-sm-4">

                <div class="h4 title">Subscribe to our Newsletter</div>
                <p>There are many variations of passages of Lorem Ipsum available</p>

                <div class="subscribe-form">
                    <form method="post" class="form-inline form-ajax">
                        <div class="input-group">
                            <input type="email" class="form-control" placeholder="Your E-mail...*" required>
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-theme"><i class="fa fa-fw fa-envelope"></i></button>
                            </div>
                        </div>
                    </form>
                </div>

                <ul class="social-big">
                    <li>
                        <a href="#">
                            <i class="icon icon-facebook fa fa-fw fa-facebook"></i>
                            <div class="text">
                                Like us
                                <span>on Facebook</span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="icon icon-rss fa fa-fw fa-rss"></i>
                            <div class="text">
                                Subscribe
                                <span>to RSS Feeds</span>
                            </div>
                        </a>
                    </li>
                </ul>

            </div>
            <!-- /Footer Column -->

        </div>
    </div>

    <div class="bottom-line">
        <div class="container">
            <div class="row">

                <!-- Copyright -->
                <div class="col-md-7 col-sm-12">
                    <p class="copyright">
                        Copyright &copy; 2015-2016 <strong>Valery Timofeev</strong>
                    </p>
                    <div class="links">
                        <a  href="#">Information</a>
                        <a  href="#">Terms of service</a>
                        <a  href="#">Private police</a>
                    </div>
                </div>
                <!-- /Copyright -->

                <!-- Footer Social -->
                <div class="col-md-5 col-sm-12">

                    <ul class="list-inline">
                        <li><a href="#" class="icon fa fa-fw fa-facebook"></a></li>
                        <li><a href="#" class="icon fa fa-fw fa-twitter"></a></li>
                        <li><a href="#" class="icon fa fa-fw fa-google-plus"></a></li>
                        <li><a href="#" class="icon fa fa-fw fa-dribbble"></a></li>
                        <li><a href="#" class="icon fa fa-fw fa-pinterest"></a></li>
                    </ul>

                    <ul class="list-inline">
                        <li><a href="#" class="icon fa fa-fw fa-phone"></a>  +1 (201) 987-1185</li>
                        <li><a href="#" class="icon fa fa-fw fa-envelope"></a> clients@example.com</li>
                        <li><a href="#" class="icon fa fa-fw fa-skype"></a> YourCompany</li>
                    </ul>

                </div>
                <!-- /Footer Social -->

            </div>
        </div>
    </div>

</footer>
<!-- /Footer -->
  </body>
</html>

app/views/posts/edit.html.erb
<!-- Page Header -->
<div class="inner-page-header">
	<div class="container">
		<div class="row">

			<!-- Page Title -->
			<div class="col-md-8">
				<h1 class="title">Edit Blog</h1>
				<div class="subtitle">You are editing post <%= @post.id %> </div>
			</div>
			<!-- /Page Title -->

			<!-- Breadcrumbs -->
			<div class="col-md-4">
				<ul class="breadcrumb">
					<li><i class="fa fa-fw fa-home"></i> <a href="<%= root_path %>">Home</a></li>
					<li><a href="<%= posts_path %>">Blog</a></li>
					<li>Edit</li>
				</ul>
			</div>
			<!-- /Breadcrumbs -->

		</div>
	</div>
</div>
<!-- /Page Header -->

<%= form_for @post do |f| %>

<!-- Main -->
<main class="main-container">

	<div class="container">
		<div class="row">

			<!-- Blog Content -->
			<div class="col-md-9">

				<!-- Posts List -->
				<div class="posts-list">

					<!-- Single Post With Image -->
					<article class="blog-post">

						<!-- Post Image -->
						<div class="image">
							<a href="images/project-01.jpg" class="image-popup">
								<div class="gallery-image">

									<%= image_tag("project-01.jpg", :alt => "") %>

								</div>
							</a>
						</div>
						<!-- /Post Image -->

						<!-- Content -->
						<div class="data">

							<!-- Post Title -->
							<label for="">Post Title:</label>
							<h2 class="title"><%= f.text_field :title %></h2>
							<!-- /Post Title -->

							<!-- Post Metadata -->
							<ul class="list-inline meta">
								<li><i class="icon fa fa-calendar"></i> January, 17, 2016</li>
								<li><i class="icon fa fa-user"></i> by <a href="#"><%= @post.author %></a></li>
								<li><i class="icon fa fa-tags"></i> <a href="#">Photography</a>, <a href="#">Illustration</a></li>
								<li><i class="icon fa fa-comments"></i> <a href="#">12 Comments</a></li>
							</ul>
							<!-- /Post Metadata -->

							<!-- Post Content -->
							<div class="content">
								<label for="">Post content:</label>
								<p>
									<%= f.text_area :content, class: 'form-control' %>
								</p>
								<blockquote>
									There are many variations of passages of Lorem Ipsum available, but the majority have
									suffered alteration in some form, by injected humour, or randomised words which don't look
									even slightly believable.
								</blockquote>

								<p>
									It is a long established fact that a reader will be distracted by the readable content of a
									page when looking at its layout. The point of using Lorem Ipsum is that it has a
									more-or-less normal distribution of letters, as opposed to using 'Content here, content
									here', making it look like readable English. Many desktop publishing packages and web page
									editors now use Lorem Ipsum as their default model text.
								</p>

								<p>
									If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything
									embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet
									tend to repeat predefined chunks as necessary, making this the first true generator on the
									Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model
									sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem
									Ipsum is therefore always free from repetition, injected humour, or non-characteristic words
									etc.
								</p>

							</div>
							<!-- /Post Content -->

						</div>
						<!-- /Content -->

						<!-- Additional -->
						<div class="row information">

							<div class="col-sm-6">
								<div class="tags">
									<a class="tag" href="#">web</a>
									<a class="tag" href="#">clean</a>
									<a class="tag" href="#">gallery</a>
								</div>
							</div>

							<div class="col-sm-6">
								<ul class="list-inline social-inline">
									<li><a href="#" class="fa fa-fw fa-facebook"></a></li>
									<li><a href="#" class="fa fa-fw fa-twitter"></a></li>
									<li><a href="#" class="fa fa-fw fa-google-plus"></a></li>
									<li><a href="#" class="fa fa-fw fa-dribbble"></a></li>
									<li><a href="#" class="fa fa-fw fa-pinterest"></a></li>
								</ul>
							</div>

						</div><br>
						<!-- /Additional -->
					<div class="text-center">						
						<button type="reset" class="btn btn-red btn-rounded">Annulé les modification</button>
						<button type="submit" class="btn btn-theme btn-rounded">Validé les modification</button>
					</div>

					</article>
					<!-- /Single Post With Image -->

				</div>
				<!-- /Posts List -->


			</div>
			<!-- /Blog Content -->

			<!-- Blog Sidebar -->
			<div class="col-md-3">

				<!-- Widget: Categories -->
				<div class="widget">

					<div class="title">Categories</div>
					<ul class="sidebar-menu">
						<li><a href="#">Photography</a></li>
						<li><a href="#">Illustration</a></li>
						<li><a href="#">Web-Design</a></li>
						<li><a href="#">Art</a></li>
						<li><a href="#">Coding</a></li>
					</ul>

				</div>
				<!-- /Widget: Categories -->

				<!-- Widget: Tags -->
				<div class="widget">

					<div class="title">Tags</div>
					<div class="tags">
						<a href="#" class="tag">web</a>
						<a href="#" class="tag">design</a>
						<a href="#" class="tag">clean</a>
						<a href="#" class="tag">minimal</a>
						<a href="#" class="tag">pixel perfect</a>
						<a href="#" class="tag">blog</a>
						<a href="#" class="tag">gallery</a>
					</div>

				</div>
				<!-- /Widget: Tags -->

				<!-- Widget: Categories -->
				<div class="widget">

					<div class="title">Meta</div>
					<ul class="sidebar-menu">
						<li><a href="#"><i class="icon fa fa-fw fa-sign-in"></i> Login</a></li>
						<li><a href="#"><i class="icon fa fa-fw fa-rss-square"></i> RSS Entries</a></li>
						<li><a href="#"><i class="icon fa fa-fw fa-comments-o"></i> RSS Comments</a></li>
					</ul>

				</div>
				<!-- /Widget: Categories -->

			</div>
			<!-- /Blog Sidebar -->

		</div>
	</div>

</main>
<!-- /Main -->

<% end %>